name: Run Cypress Tests

on:
  push:
    branches:
      - cypress

jobs:
  cypress-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          cd test
          npm install

      # 4. Ejecutar los tests de Cypress
      - name: Run Cypress Tests
        run: |
          cd test
          npx cypress run 

      # 5. Publicar resultados en GitHub
      - name: Publish cypress/videos 
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-v
          path: test/cypress/videos 

      # 6. Publicar resultados en GitHub
      - name: Publish cypress/screenshots 
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-s
          path: test/cypress/screenshots 
