name: Run Cypress Tests

on:
  push:
    branches:
      - cypress


jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          cd test
          npm install

      # 4. Ejecutar los tests de Cypress
      - name: Run Cypress Tests
        run: |
          cd test
          npx cypress run 

      # 5. (Opcional) Publicar resultados en GitHub
      - name: Publish Cypress Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: test/cypress/videos 
